language: minimal

services:
  - docker

script:
  - docker build -t registry.aragon.codes/miguel.aragon.codes .

deploy:
  provider: script
  script: bash scripts/push-image.sh
  on:
    branch: master